---
kind: Service
apiVersion: v1
metadata:
  name: gce-webapp-service
spec:
  selector:
    app: gce-webapp
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30002
  type: LoadBalancer



---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gce-webapp-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gce-webapp
    spec:
      containers:
        - name: gce-webapp
          image: rafaelapb/gce-webapp:v1.1
          ports:
            - containerPort: 8080
